name: new
online: true
muted: false
god: false
afk: false
gamemode: 0
invisible: false
viewingInventory: false
update: false
nickname: new
chatChannel: eq
listenChannels:
- eq
ipAddress: {}
horn:
  left: {}
  right: {}
  on: false
firstLogon: n/a
lastLogon: n/a
lastLogout: n/a
warps:
  other:
    back: {}
    home: {}
    offline: {}
inventory: {}
ban:
  banned: false
  banReason: {}
warnings: {}
