name: new
online: true
muted: false
god: false
afk: false
invisible: false
viewingInventory: false
nickname: new
chatChannel: eq
listenChannels:
- eq
ipAddress: {}
ban:
  banned: false
  banReason: {}
warnings:
  warning1: {}
  warning2: {}
  warning3: {}
firstLogon: n/a
lastLogon: n/a
lastLogout: n/a
inventory: {}
