main: com.github.CorrieKay.PinkiePiesPlethoraOfPoniPlugins.Mane
name: PinkiePiesPlethoraOfPoniPlugins
author: CorrieKay
version: 0.1
commands:
    afk:
        description: toggles manual afk
        usage: /afk toggles
        permission: pppopp.afk
        executor: Afk Handler
    hide:
        description: toggles hidden status silently
        usage: /hide
        permission: pppopp.hide
        executor: Invisibility Handler
    fakehide:
        description: toggles hidden status publicly, with quit/join messages
        usage: /fakehide
        permission: pppopp.hide
        executor: Invisibility Handler
    nopickup:
        description: toggles no pickup of items
        usage: /nopickup
        aliases: np
        permission: pppopp.nopickup
        executor: Invisibility Handler
    invsee:
        description: veiws another users inventory. if the user is online, you can view and edit in real time
        usage: /invsee <player>
        permission: pppopp.invsee
        executor: Inventory See Handler
    commitinventorychange:
        description: commits an inventory change to an offline player
        usage: /commitinventorychange <player>
        permission: pppopp.invsee
        aliases: cic
        executor: Inventory See Handler
    watertoggle:
        description: toggles waterflow
        usage: /watertoggle
        permission: pppopp.waterflowtoggle
        executor: Protection Handler
    lavatoggle:
        description: toggles lavaflow
        usage: /lavatoggle
        permission: pppopp.lavaflowtoggle
        executor: Protection Handler
    ban:
        description: bans a player
        usage: /ban <player> <reason>
        permission: pppopp.ban
        executor: BanHammer
    unban:
        description: unbans a player
        usage: /unban <player>
        permission: pppopp.ban
        executor: BanHammer
    kick:
        description: kicks a player
        usage: /kick <player> <reason>
        permission: pppopp.kick
        executor: BanHammer
    warn:
        description: warns a player
        usage: /warn <player> <reason>
        permission: pppopp.warn
        executor: BanHammer
    convertbans:
        description: converts all bans into PPPOPP bans
        usage: /convertbans
        permission: pppopp.ban
        executor: BanHammer
    warnings:
        description: gets your warnings
        usage: /warnings
        permission: pppopp.warnings
        executor: BanHammer
permissions:
    pppopp.afk:
        default: false
    pppopp.hide:
        default: false
    pppopp.invsee:
        default: false
    pppopp.nopickup:
        default: false
    pppopp.blockwarn:
        default: false
    pppopp.waterflowtoggle:
        default: false
    pppopp.lavaflowtoggle:
        default: false
    pppopp.ban:
        default: false
    pppopp.kick:
        default: false
    pppopp.warn:
        default: false