main: com.github.CorrieKay.PinkiePiesPlethoraOfPoniPlugins.Mane
name: PinkiePiesPlethoraOfPoniPlugins
author: CorrieKay
version: 0.1
commands:
    afk:
        description: toggles manual afk
        usage: /afk toggles
        permission: pppopp.afk
    hide:
        description: toggles hidden status silently
        usage: /hide
        permission: pppopp.hide
    fakehide:
        description: toggles hidden status publicly, with quit/join messages
        usage: /fakehide
        permission: pppopp.hide
    nopickup:
        description: toggles no pickup of items
        usage: /nopickup
        aliases: np
        permission: pppopp.nopickup
    invsee:
        description: veiws another users inventory. if the user is online, you can view and edit in real time
        usage: /invsee <player>
        permission: pppopp.invsee
    commitinventorychange:
        description: commits an inventory change to an offline player
        usage: /commitinventorychange <player>
        permission: pppopp.invsee
        aliases: cic
    watertoggle:
        description: toggles waterflow
        usage: /watertoggle
        permission: pppopp.waterflowtoggle
    lavatoggle:
        description: toggles lavaflow
        usage: /lavatoggle
        permission: pppopp.lavaflowtoggle
permissions:
    pppopp.afk:
        default: false
    pppopp.hide:
        default: false
    pppopp.invsee:
        default: false
    pppopp.nopickup:
        default: false
    pppopp.blockwarn:
        default: false
    pppopp.waterflowtoggle:
        default: false
    pppopp.lavaflowtoggle:
        default: false