main: com.github.CorrieKay.PinkiePiesPlethoraOfPoniPlugins.Mane
name: PinkiePiesPlethoraOfPoniPlugins
author: CorrieKay
version: 0.1
commands:
    afk:
        description: toggles manual afk
        usage: /afk toggles
        permission: pppopp.afk
    hide:
        description: toggles hidden status silently
        usage: /hide
    fakehide:
        description: toggles hidden status publicly, with quit/join messages
        usage: /fakehide
permissions:
    pppopp.afk:
        default: false
    pppopp.hide:
        default: false